### ISSUE TITLE
REST Todo

### ISSUE THREAD

**Issue by ximex** [MITG13/geocoding-project#1]
- [x] Define Request URLs
- [x] Define JSON Object for data exchange
- [x] Research for Javascript Plugins
- [x] Parse JSON Objects from C# Lib
